apiVersion: v1
kind: Service
metadata:
  name: sql-server-service
  namespace: store-apps
spec:
  type: NodePort 
  selector:
    app: sql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 31433 # Цей порт буде відкритий на вашому комп'ютері